platform :ios, '7.0' 
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.7'
pod 'MJExtension'
pod 'MJRefresh'
pod 'FMDB'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'UMengSocial'
pod 'RRUMessage'
pod 'mp3lame-for-ios', '~> 0.1.1'