use_frameworks!
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.7'
pod 'MJExtension'
pod 'MJRefresh'
pod 'FMDB'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'UMengSocial'
pod 'RRUMessage'
pod 'mp3lame-for-ios', '~> 0.1.1'
pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
